# -*- coding: utf-8 -*-
"""Linear-classfier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fQFU2eLByg2I9Ki-De86y7lwF_Bb5LY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('train.csv')

print("Data Preview:")
print(df.head())

X = df[['battery_power', 'ram']].values
y = df['price_range'].values

X = (X - X.mean(axis=0)) / X.std(axis=0)

n_samples, n_features = X.shape
n_classes = len(np.unique(y))

print("Jumlah data:", n_samples)
print("Jumlah fitur:", n_features)
print("Jumlah kelas:", n_classes)

def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

def cross_entropy(y_true, y_pred):
    return -np.log(y_pred[y_true] + 1e-9)

def train_sgd(X, y, lr=0.01, epochs=20):
    W = np.zeros((n_classes, n_features))
    b = np.zeros(n_classes)

    for epoch in range(epochs):
        total_loss = 0

        for i in range(len(X)):
            x_i = X[i]
            y_i = y[i]

            scores = np.dot(W, x_i) + b
            probs = softmax(scores)

            loss = cross_entropy(y_i, probs)
            total_loss += loss

            # update SGD
            for c in range(n_classes):
                error = probs[c] - (1 if c == y_i else 0)
                W[c] -= lr * error * x_i
                b[c] -= lr * error

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return W, b

W, b = train_sgd(X, y)


def predict(X, W, b):
    preds = []
    for x in X:
        scores = np.dot(W, x) + b
        probs = softmax(scores)
        preds.append(np.argmax(probs))
    return np.array(preds)

y_pred = predict(X, W, b)
accuracy = np.mean(y_pred == y)

print("\nAkurasi model:", accuracy)


def plot_decision_boundary(X, y, W, b):
    print("Menampilkan decision boundary...")

    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100),
                         np.linspace(y_min, y_max, 100))

    grid = np.c_[xx.ravel(), yy.ravel()]

    Z = predict(grid, W, b)
    Z = Z.reshape(xx.shape)

    plt.figure()
    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(X[:, 0], X[:, 1], c=y)
    plt.title("Decision Boundary")
    plt.xlabel("battery_power")
    plt.ylabel("ram")
    plt.show()

plot_decision_boundary(X, y, W, b)

z = np.array([2.0, 1.0, 0.1, 3.0])
print("\nContoh Softmax:")
print(softmax(z))