# -*- coding: utf-8 -*-
"""LinearRegression_SGD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YO1owxafw_Wamyte3pWnlhcim_j7Nvmz
"""

# 1. Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 2. Upload file dari user
from google.colab import files
uploaded = files.upload()

# 3. Baca file (ambil nama file yang diupload)
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# 4. Ambil fitur dan target
X = df['bmi'].values
y = df['charges'].values

# Normalisasi
X = (X - X.mean()) / X.std()

# 5. Inisialisasi parameter
w = 0
b = 0
lr = 0.01
epochs = 1000

n = len(X)

# 6. SGD Training
for epoch in range(epochs):
    for i in range(n):
        y_pred = w * X[i] + b

        error = y_pred - y[i]

        dw = error * X[i]
        db = error

        w = w - lr * dw
        b = b - lr * db

# 7. Prediksi
y_pred_all = w * X + b

# 8. Visualisasi
plt.scatter(X, y, label='Data Asli')
plt.plot(X, y_pred_all, label='Regresi')
plt.xlabel('BMI (Normalized)')
plt.ylabel('Charges')
plt.title('Linear Regression dengan SGD')
plt.legend()
plt.show()

# 9. Output parameter
print("Weight:", w)
print("Bias:", b)

# 10. Evaluasi (optional)
mse = np.mean((y - y_pred_all)**2)
print("MSE:", mse)